In [2]:
import numpy as np
A= np.array([[1,2,9],[3,4,6]])
B =np.array([[6,9], [83,3], [8,8]])

# print('A+B=', A+B)
# Produit matriciel
print("A @ B =\n", A @ B)
# Transposée de A
print("A transposée =\n", A.T)
# Rang de A
rank_A = np.linalg.matrix_rank(A)
print("Rang de A =", rank_A)

A @ B =
 [[244  87]
 [398  87]]
A transposée =
 [[1 3]
 [2 4]
 [9 6]]
Rang de A = 2


In [22]:
c = np.array([[3,4,5],[3,62,7]])
d = np.array([[7636,29,93],[8472,9,32]])
print(d)
print(c.shape)
print(d.shape)
print(c+d)
# print(c@d) cannot be because l*m m*r the m is different 

[[7636   29   93]
 [8472    9   32]]
(2, 3)
(2, 3)
[[7639   33   98]
 [8475   71   39]]


produit scalaire  et transpo

In [23]:
vec1 = np.array([3,56,7,2,6,8])
vec2 =np.array([37,6,2,5,7,3])
produitsc = np.dot(vec1, vec2)
print(produitsc)
print(vec1.mean())
print(np.mean(vec2))
##les deux marchent c un objet de type numpy anyway
print(vec2.min())
print('transpose de d: \n', d.T )


537
13.666666666666666
10.0
2
transpose de d: 
 [[7636 8472]
 [  29    9]
 [  93   32]]


In [30]:
pair = np.arange(0,10 , 2)
print(pair)
i =np.eye(765,908)
print(f'eye : {i}')

[0 2 4 6 8]
eye : [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


slicing et indexation :

In [42]:
mat = np.array([[10, 20, 30], [40, 50, 60]])
#acces a une ligne :
print(mat[0])
#acces a une ligne :
print(mat[:,1 ])
#sous matrice : 
print('sous matrice : \n', mat[:, 1:3])
print(np.linalg.norm(mat))

[10 20 30]
[20 50]
sous matrice : 
 [[20 30]
 [50 60]]
95.39392014169457


exo :

In [ ]:
a = np.array([2,3,6,4])
print('sum :', a.sum())
print('mean', a.mean() )
print('product', a.prod() )

sum : 15
mean 3.75
prouct 144
