array 1111111
      1 0 0 1
      1009001
      1 0 0 1
      1111111


In [3]:
import numpy as np
array = np.ones((5,5))

array[1, 1 : 4] = 0
array[3, 1 : 4] = 0
array[2, 1 : 4 :2] = 0
array[2,2]= 9
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [4]:
# autre solution : 
array = np.ones((5,5))
armidl = np.zeros((3,3))
armidl[1,1]= 9  
array[1 : 4, 1: 4]= armidl
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


exercice de gpt

In [5]:
arr = np.random.randint(10, 50, size=100)
print(arr)
arriden = np.identity(5)
print(arriden)
arr= np.arange(1, 21).reshape(4, 5)
print(arr)
#part3
arr = np.random.randint(1,83, size=16)
arr = arr.reshape(4,4)
print(arr)
print(arr.reshape(2,2,4))
print(np.arange(6).reshape(2,3))

[29 10 11 47 13 21 24 26 25 20 23 31 23 17 32 45 29 39 49 19 41 32 46 27
 11 14 14 33 19 37 36 47 32 46 39 32 46 33 10 18 24 11 42 27 33 39 20 38
 22 39 10 46 39 49 43 32 28 37 27 43 42 15 20 24 13 22 31 41 24 13 16 29
 34 44 11 23 43 46 32 14 22 13 13 32 41 12 13 46 24 34 33 12 49 17 43 16
 16 25 15 38]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[33 24  6 18]
 [10 62 28 51]
 [52 16  2 19]
 [ 1  9 22 47]]
[[[33 24  6 18]
  [10 62 28 51]]

 [[52 16  2 19]
  [ 1  9 22 47]]]
[[0 1 2]
 [3 4 5]]


agregation and broadcasting :

In [6]:
arr = np.array([[5, 1, 3], [2, 4, 6]])
print(arr+ arr)
print(arr.sum())
print(arr.mean(axis=0))#moyenne par colonne
print(arr.mean(axis=1)) #moyenne par row
print(arr.min())
#soit
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([10, 20, 30])
print(A+B)
print(A*B)
print(A/B)

[[10  2  6]
 [ 4  8 12]]
21
[3.5 2.5 4.5]
[3. 4.]
1
[[11 22 33]
 [14 25 36]]
[[ 10  40  90]
 [ 40 100 180]]
[[0.1  0.1  0.1 ]
 [0.4  0.25 0.2 ]]


un peu plus dur : 


In [7]:
# 1. Crée un tableau 1D de 50 entiers aléatoires entre 1 et 100.
# 2. Remplace tous les nombres impairs par -1.
# 3. Compte combien de valeurs sont supérieures à 70.
# 4. Extrais les 5 plus grands éléments du tableau.
arr = np.random.randint(1,100, size=50)
arr[arr%2==0]=-1
print(arr)
np.count_nonzero(arr[arr>70])
print(np.partition(arr,-2 )[-2 :])


[-1 -1  3 -1 -1 77 -1 -1 59 -1 21 -1 -1 -1 -1 -1 -1 13 23 -1 59 93 11 -1
 43 89 -1 11 71 -1 -1  5 -1 -1 -1 61 -1 85 -1 -1 21 -1 -1 33 21 69 -1 -1
 -1 -1]
[89 93]


In [15]:
# 1. Crée un tableau de forme (3, 1) contenant [1, 2, 3].
# 2. Crée un autre tableau de forme (1, 4) contenant [10, 20, 30, 40].
# 3. Fais une addition entre les deux (broadcasting).
# 4. Que donne le résultat ? Quelle est sa forme ?
arr = np.arange(1, 4).reshape((3,1))
print(arr)
arr2 =np.arange(10, 41, 10).reshape((1,4))
print(arr+arr2)
print((arr+arr2).shape)

[[1]
 [2]
 [3]]
[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]
(3, 4)
