array 1111111
      1 0 0 1
      1009001
      1 0 0 1
      1111111


In [17]:
import numpy as np
array = np.ones((5,5))

array[1, 1 : 4] = 0
array[3, 1 : 4] = 0
array[2, 1 : 4 :2] = 0
array[2,2]= 9
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# autre solution : 
array = np.ones((5,5))
armidl = np.zeros((3,3))
armidl[1,1]= 9  
array[1 : 4, 1: 4]= armidl
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


exercice de gpt

In [48]:
arr = np.random.randint(10, 50, size=100)
print(arr)
arriden = np.identity(5)
print(arriden)
arr= np.arange(1, 21).reshape(4, 5)
print(arr)
#part3
arr = np.random.randint(1,83, size=16)
arr = arr.reshape(4,4)
print(arr)
print(arr.reshape(2,2,4))
print(np.arange(6).reshape(2,3))

[41 31 27 44 19 19 36 43 34 36 46 32 20 34 33 42 13 14 20 29 31 10 31 17
 47 32 49 28 20 37 45 29 27 32 16 32 39 22 46 30 47 45 43 20 39 24 39 20
 17 48 20 44 25 12 21 33 39 30 28 38 40 26 23 43 10 33 49 25 36 44 43 39
 10 24 42 47 40 28 12 37 48 48 39 21 24 14 46 49 12 41 24 30 13 36 40 34
 49 25 44 11]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[54 75 32  8]
 [ 7 15 73 36]
 [23 23 27 69]
 [14 30 58 65]]
[[[54 75 32  8]
  [ 7 15 73 36]]

 [[23 23 27 69]
  [14 30 58 65]]]
[[0 1 2]
 [3 4 5]]


agregation and broadcasting :

In [65]:
arr = np.array([[5, 1, 3], [2, 4, 6]])
print(arr+ arr)
print(arr.sum())
print(arr.mean(axis=0))#moyenne par colonne
print(arr.mean(axis=1)) #moyenne par row
print(arr.min())
#soit
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([10, 20, 30])
print(A+B)
print(A*B)
print(A/B)

[[10  2  6]
 [ 4  8 12]]
21
[3.5 2.5 4.5]
[3. 4.]
1
[[11 22 33]
 [14 25 36]]
[[ 10  40  90]
 [ 40 100 180]]
[[0.1  0.1  0.1 ]
 [0.4  0.25 0.2 ]]


un peu plus dur : 


In [109]:
# 1. Crée un tableau 1D de 50 entiers aléatoires entre 1 et 100.
# 2. Remplace tous les nombres impairs par -1.
# 3. Compte combien de valeurs sont supérieures à 70.
# 4. Extrais les 5 plus grands éléments du tableau.
arr = np.random.randint(1,100, size=50)
arr[arr%2==0]=-1
print(arr)
np.count_nonzero(arr[arr>70])
print(np.partition(arr,-2 )[-2 :])


[53 21 -1 -1 95 -1 43 -1 -1 -1 75 27 47 -1 73 91 -1  5 47 49 -1 31 -1 47
 65 29 -1 -1 81 -1 15 -1 59 19 17 17 87 -1 67 -1 -1 85 -1 -1 11 23 69 17
 -1 87]
[91 95]
